<div class="loginSignupScop" data-bind="scope:'loginSignupScop'">
    <a rel="nofollow" style="display:none;" class="loginBtnTop" data-bind="visible: isLoggedIn() === false, click: showPopupButton"><?= __('Log In') ?></a>
    <a rel="nofollow" style="display:none;" class="accountBtnTop"  data-bind="visible: isLoggedIn, attr:{href: getSiteUrl('customer/account')}">
        Hi,<span class="accountName" data-bind="text: customerData().fullname"></span>
    </a>
    <div data-bind="visible: isLoggedIn" style="display:none;">
        <div class="quick-login-dropdown">
            <ul>
                <li>&nbsp;</li>
                <li class="account">
                    <a rel="nofollow" data-bind="attr:{href: getSiteUrl('customer/account/edit')}">
                        <span><?= __('Account Information') ?></span>
                    </a>
                </li>
                <li class="order">
                    <a rel="nofollow" data-bind="attr:{href: getSiteUrl('sales/order/history')}">
                        <span><?= __('Order history') ?></span>
                    </a>
                </li>
                <li class="log-out">
                    <a rel="nofollow" data-bind="click: koLogout, attr:{href: getSiteUrl('customer/account/logout')}">
                        <span><?= __('Log out') ?></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="loginSignupContainer" data-bind="if: isLoginSignupShow, css: { 'modal-animation': isLoginSignupShow() == true}" style="display:none;">
        <div class="lordhairModal modal-background">
            <span class="helper"></span>
            <div class="loginSignUpInner">
                <div class="popupCloseButton close" data-bind="click: popupCloseButton">×</div>
                <div class="modal-body-wrap">
                    <div class="modal-body-part-wrap">
                        <div class ="whiteBg" style="display:block;" data-bind="visible: isInitLoading" id="ajaxOverlay">
                            <div class="cv-spinner">
                                <span class="spinner"></span>
                            </div>
                        </div>
                        <!-- ko template: getTemplate() --><!-- /ko -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    requirejs(['jquery'], 
    function($) {
        'use strict';
        const getSiteUrl = '<?php echo $block->getBaseUrl(); ?>';
        const lordAjaxCheckLoggedIn = `${getSiteUrl}lordajaxloginsign/ajax/checkuserexist`;

        $(document).on("click",".loginBtnTop",function(event) {
            event.preventDefault();
            $(".loginSignupContainer").show();
            $(".loginSignupContainer").addClass('modal-animation');
            $("input[name=loginEmailMobile]").focus();
            $('#loginPassword').focus();
            $('ul.tabs li:nth-child(1)').focus();
            $("input[name=regFirstName]").focus();
        }); 
        
        $(document).on("click","ul.tabs li:nth-child(1)",function() {
            $('#loginPassword').focus();
            $("input[name=loginEmailMobile]").focus();
        }); 
        
        $(document).on("click","ul.tabs li:nth-child(2)",function() {
            $('#loginPassword').focus();
            $("input[name=regFirstName]").focus();
        });
       
        function addClickListenersBefore(event) {
            var getCurrentUrl = window.location.href;
            if (getCurrentUrl.includes("customer/account/login") == false && getCurrentUrl.includes("customer/account/create") == false && getCurrentUrl.includes("customer/account/forgotpassword") == false) {
                var lordhairModal = document.querySelector(".lordhairModal");
                if (event.target == lordhairModal) {
                    $(".loginSignupContainer").hide();
                    $(".loginSignupContainer").removeClass('modal-animation');
                    $(".quick-login").parents('.right-column').removeAttr('style');
                }
            }
        }

        window.addEventListener('click', addClickListenersBefore);

        $.ajax({
            type: "POST",
            url: lordAjaxCheckLoggedIn,
            async: false,
            data: {
                'checkLoggedIn' : true,
            },
            dataType: "json",
            success: function(response) {
                if (!response.errors) {
                    $(".loginBtnTop").hide();
                    $(".accountBtnTop").show();
                    $(".accountName").text(response.customer.fullname);
                } else{
                    $(".loginBtnTop").show();
                    $(".accountBtnTop").hide();
                }
            },
            error: function(xhr, status, error){
                if (status === 0) {
                    alert('Not connect.n Verify Network.');
                } else if (status == 404) {
                    alert('Requested page not found. [404]');
                } else if (status == 500) {
                    alert('Internal Server Error [500].');
                } else if (exception === 'parsererror') {
                    alert('Requested JSON parse failed.');
                } else if (exception === 'timeout') {
                    alert('Time out error.');
                } else if (exception === 'abort') {
                    alert('Ajax request aborted.');
                } else {
                    alert('Uncaught Error.n' + xhr.statusText);
                }
            }
        });
        
        $(document).on("click",".new-like-btn",function(event) {
            event.preventDefault();
            $.ajax({
                type: "POST",
                url: lordAjaxCheckLoggedIn,
                async: false,
                data: {
                    'checkLoggedIn' : true,
                },
                dataType: "json",
                success: function(response) {
                    if (!response.errors) {
                        window.location.replace(`${getSiteUrl}customer/account`);
                    } else{
                        $(".quick-login").parents('.right-column').show();
                        $(".loginBtnTop").trigger("click");
                    }
                },
                error: function(xhr, status, error){
                    if (status === 0) {
                        alert('Not connect.n Verify Network.');
                    } else if (status == 404) {
                        alert('Requested page not found. [404]');
                    } else if (status == 500) {
                        alert('Internal Server Error [500].');
                    } else if (exception === 'parsererror') {
                        alert('Requested JSON parse failed.');
                    } else if (exception === 'timeout') {
                        alert('Time out error.');
                    } else if (exception === 'abort') {
                        alert('Ajax request aborted.');
                    } else {
                        alert('Uncaught Error.n' + xhr.statusText);
                    }
                }
            });
        });
    });
</script>
<script type="text/x-magento-init">
    { 
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "loginSignupScop": {
                        "component": "Lordhair_LoginSignup/js/viewModel"
                    }
                }
            }
        }
    }
</script>