<?php
$paypalUserData = $block->getData('paypalUserData');
if ($paypalUserData) {
?>
    <ul>
        <li class="account">
            <a rel="nofollow" href="<?php echo $this->getUrl('customer/account/edit');?>">
                <span><?php echo __('Account Information');?></span>
            </a>
        </li>
        <li>
            <a rel="nofollow" href="<?php echo $this->getUrl('');?>">
                <span><?php echo __('Home');?></span>
            </a>
        </li>
        <li>
            <a rel="nofollow" href="<?php echo $this->getUrl('why-lordhair.html');?>">
                <span><?php echo __('Why Shop At Lordhair');?></span>
            </a>
        </li>
    </ul>
<?php
}