<?php
   $productData = $block->getData();
   $product = $productData['data']['product'];
   $getPostParams = $productData['data']['getPostParams'];
   $productId = $product->getID();
   $getCurrentAttributes = $block->_getCurrentAttributesCall($product,$getPostParams);
   $getPubCustomizationUrl = $block->getSiteMainUrl().'media/customization/';
   $getPubColrUrl = $block->getSiteMainUrl().'media/customization/colors/';

   if ($getCurrentAttributes['attributeName'] == 'm_hair_color') {
      $block->setOptionLevelToSession('1_1');
      $block->setDoneOrNotStepToSession('');
       $block->setSubTitleToSession(__('We recommend to send us your hair sample to reduce the color error.'));
      foreach ($getCurrentAttributes['attributValue'] as $attribute) {
         $activeClass = '';
         $activeAttrOption = $block->_checkAlreadyInSession($getCurrentAttributes['attributeName'],$attribute);
         $newAttribute = preg_replace("/[^a-zA-Z]/", "", $attribute);
         $activeAttrOption = preg_replace("/[^a-zA-Z]/", "", $activeAttrOption);
         if ($activeAttrOption && strcmp(trim($activeAttrOption), trim($newAttribute)) == 0) {
            $activeClass = 'active current';
         }
         $getImagesByAttrName = $block->getImagesByAttrName($attribute);
         $mainImage = isset($getImagesByAttrName['mainImage']) ?  $getImagesByAttrName['mainImage'] : '';
         $thumbImage = isset($getImagesByAttrName['thumbImage']) ?  $getImagesByAttrName['thumbImage'] : '';
         $getPriceRule = $block->getPriceRule($product,$attribute);
         $getFrmtdPriceRule = $block->getFrmtdPriceRule($getPriceRule);
         $getPriceRule = $this->helper('Lordhair\Customizations\Helper\Data')->getDataPriceRule($getPriceRule);
 ?>
         <div class="base-item checkboxWrap" data-level="1" data-optionLevel="1_1" data-currentattr="m_hair_color" data-currentparent="m_hair_color_main" data-src="<?= $getPubCustomizationUrl.$mainImage ?>">
            <div class="base-item-inner checkbox <?= $activeClass ?>">
               <div class="base-img">
                  <img alt="<?= __(trim($attribute)) ?>" src="<?= $getPubCustomizationUrl.$thumbImage ?>">
               </div>
               <div class="base-details" data-price="<?= $getPriceRule ?>">
                  <p class="attrOptionTitle">
                     <span><?= __(trim($attribute)) ?></span>
                     <?php
                        if ($getFrmtdPriceRule && $getFrmtdPriceRule != '') {
                           echo '<span class="upgradePrice">'.$getFrmtdPriceRule.'</span>';
                        }
                     ?>
                  </p>
               </div>
               <textarea class="attrOptionTitleValue"><?= $attribute ?></textarea>
            </div>
         </div>
     <?php }
   }

   if (strcmp(trim($getCurrentAttributes['attributeName']), 'Use your color code') == 0) {
      $block->setOptionLevelToSession('3_2');
      $block->setDoneOrNotStepToSession('half');
       $block->setSubTitleToSession(__('The hair color pictures are only for reference. Please be aware there might be color differences due to different monitors or screens.'));
      foreach ($getCurrentAttributes['mulipleOptions']['childOption'] as $attribute) {
         if ($attribute['optionTitle'] != '') {
            $activeClass = '';
            $activeAttrOption = $block->_checkAlreadyInSession($attribute['attrName'],$attribute['optionTitle']);
            if ($activeAttrOption && strcmp(trim($activeAttrOption), trim($attribute['optionTitle'])) == 0) {
               $activeClass = 'active current';
            }
            $getImagesByAttrName = $block->getImagesByAttrName($attribute['optionTitle']);
            $mainImage = isset($getImagesByAttrName['mainImage']) ?  $getImagesByAttrName['mainImage'] : '';
            $thumbImage = isset($getImagesByAttrName['thumbImage']) ?  $getImagesByAttrName['thumbImage'] : '';
            $getPriceRule = $block->getPriceRule($product,$attribute['optionTitle']);
            $getFrmtdPriceRule = $block->getFrmtdPriceRule($getPriceRule);
            $getPriceRule = $this->helper('Lordhair\Customizations\Helper\Data')->getDataPriceRule($getPriceRule);
   ?>
            <div class="base-item checkboxWrap" data-level="2" data-optionLevel="3_2" data-currentattr="<?= $attribute['attrName'] ?>" data-currentparent="m_hair_color" data-src="<?= $getPubColrUrl.$mainImage ?>">
               <div class="base-item-inner checkbox <?= $activeClass ?>">
                  <div class="base-img">
                     <img alt="<?= __(trim($attribute['optionTitle'])) ?>" src="<?= $getPubColrUrl.$thumbImage ?>">
                  </div>
                  <div class="base-details" data-price="<?= $getPriceRule ?>">
                     <p class="attrOptionTitle">
                        <span><?= __(trim($attribute['optionTitle'])) ?></span>
                        <?php
                           if ($getFrmtdPriceRule && $getFrmtdPriceRule != '') {
                              echo '<span class="upgradePrice">'.$getFrmtdPriceRule.'</span>';
                           }
                        ?>
                     </p>
                  </div>
                  <textarea class="attrOptionTitleValue"><?= $attribute['optionTitle'] ?></textarea>
               </div>
            </div>
   <?php
         }
      }
   }

   if (strcmp(trim($getCurrentAttributes['attributeName']), 'Please refer to my special instructions') == 0) {
      $block->setOptionLevelToSession('4_2');
      $block->setDoneOrNotStepToSession('half');
      $activeAttrOption = $block->_checkAlreadyInSession('m_hair_color_special','');
      $block->setSubTitleToSession(__('Please describe additional instruction for hair color'));
?>
      <div class="base-item textbox" data-level="2" data-optionLevel="4_2" data-currentattr="m_hair_color_special" data-currentparent="m_hair_color" data-src="" style="width:100%">
         <textarea class="unrequired hair_color_additional" name="hair_color_additional" rows="3" cols="80" placeholder="Please type in your additional instruction."><?= $activeAttrOption ?></textarea>
      </div>
<?php
   }
